# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gleepads' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gleepads
pod 'SwiftVideoBackground', '~> 3.0'

#pod 'VideoSplashKit', :git => 'https://github.com/svtek/VideoSplashKit/VideoSplashKit.git', :branch => 'swift4'



end
